# gemini_sre_agent/core/types/__init__.py

"""
Core type definitions for the Gemini SRE Agent system.

This package provides comprehensive type aliases, protocols, and utilities
for type-safe development across all components.
"""

from .base import (
    ConfigDict,
    ConfigValue,
    Configurable,
    Content,
    ContentEncoding,
    ContentType,
    Deserializable,
    Duration,
    ErrorCode,
    ErrorDetails,
    ErrorMessage,
    Identifiable,
    JsonDict,
    JsonList,
    JsonValue,
    LogContext,
    LogLevel,
    LogMessage,
    Loggable,
    MetricName,
    MetricTags,
    MetricTimestamp,
    MetricValue,
    Priority,
    ProcessingStatus,
    RequestId,
    ResponseId,
    SessionId,
    Serializable,
    Stateful,
    Timestamp,
    Timestamped,
    Timeout,
    UserId,
    Validatable,
    create_type_safe_dict,
    ensure_json_value,
    is_json_value,
)
from .agent import (
    AgentCapabilities,
    AgentContext,
    AgentId,
    AgentMetadata,
    AgentName,
    AgentRequest,
    AgentResponse,
    AgentStatus,
    AgentT,
    AnalysisAgent,
    AnalysisResponse,
    BaseAgent,
    ConfigurableAgent,
    CoordinationChannel,
    CoordinationEvent,
    CoordinationMessage,
    LoggableAgent,
    OperationStatus,
    OperationType,
    PromptContext,
    PromptTemplate,
    PromptVariables,
    RemediationAgent,
    RemediationResponse,
    RequestT,
    RequestType,
    ResponseConfidence,
    ResponseContent,
    ResponseMetadata,
    ResponseT,
    ResponseType,
    StateKey,
    StateSnapshot,
    StateValue,
    StatefulAgent,
    TriageAgent,
    TriageResponse,
    WorkflowId,
    WorkflowStatus,
    WorkflowStep,
    create_agent_context,
    validate_agent_request,
    validate_agent_response,
)
from .llm import (
    ChatProvider,
    ChatRequest,
    ChatResponse,
    CompletionProvider,
    CompletionRequest,
    CompletionResponse,
    ContentFormat,
    ContentType as LLMContentType,
    CostBreakdown,
    CostPerToken,
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingResponse,
    ErrorCode as LLMErrorCode,
    ErrorType,
    Latency,
    LLMConfig,
    LLMModel,
    LLMProvider,
    LLMRequest,
    LLMResponse,
    Message,
    ModelCapability,
    ModelConfig,
    ModelId,
    ModelStatus,
    ModelT,
    ModelType,
    ProviderConfig,
    ProviderId,
    ProviderStatus,
    ProviderT,
    ProviderType,
    RateLimit,
    RequestRole,
    ResponseRole,
    ResponseT as LLMResponseT,
    RetryAfter,
    StreamingChunk,
    StreamingResponse,
    Throughput,
    TokenCount,
    TokenUsage,
    TotalCost,
    calculate_token_cost,
    create_message,
    create_usage_dict,
    validate_model_config,
)

__all__ = [
    # Base types
    "JsonValue",
    "JsonDict", 
    "JsonList",
    "ConfigDict",
    "ConfigValue",
    "Content",
    "ContentType",
    "ContentEncoding",
    "LogLevel",
    "LogMessage",
    "LogContext",
    "AgentId",
    "AgentName",
    "AgentStatus",
    "ModelId",
    "ProviderId",
    "RequestId",
    "ResponseId",
    "SessionId",
    "UserId",
    "Priority",
    "ProcessingStatus",
    "Timestamp",
    "Duration",
    "Timeout",
    "ErrorCode",
    "ErrorMessage",
    "ErrorDetails",
    "MetricName",
    "MetricValue",
    "MetricTags",
    "MetricTimestamp",
    
    # Base protocols
    "Serializable",
    "Deserializable",
    "Identifiable",
    "Timestamped",
    "Configurable",
    "Stateful",
    "Loggable",
    "Validatable",
    
    # Base utilities
    "is_json_value",
    "ensure_json_value",
    "create_type_safe_dict",
    
    # Agent types
    "AgentT",
    "RequestT",
    "ResponseT",
    "AgentContext",
    "AgentMetadata",
    "AgentCapabilities",
    "RequestType",
    "ResponseType",
    "OperationType",
    "OperationStatus",
    "PromptTemplate",
    "PromptVariables",
    "PromptContext",
    "ResponseContent",
    "ResponseMetadata",
    "ResponseConfidence",
    "StateKey",
    "StateValue",
    "StateSnapshot",
    "CoordinationMessage",
    "CoordinationChannel",
    "CoordinationEvent",
    "WorkflowId",
    "WorkflowStep",
    "WorkflowStatus",
    
    # Agent protocols
    "BaseAgent",
    "AgentRequest",
    "AgentResponse",
    "StatefulAgent",
    "ConfigurableAgent",
    "LoggableAgent",
    "TriageAgent",
    "AnalysisAgent",
    "RemediationAgent",
    "TriageResponse",
    "AnalysisResponse",
    "RemediationResponse",
    
    # Agent utilities
    "create_agent_context",
    "validate_agent_request",
    "validate_agent_response",
    
    # LLM types
    "ProviderT",
    "ModelT",
    "LLMResponseT",
    "ProviderType",
    "ProviderStatus",
    "ModelType",
    "ModelStatus",
    "ModelCapability",
    "RequestRole",
    "ResponseRole",
    "LLMContentType",
    "ContentFormat",
    "TokenCount",
    "TokenUsage",
    "CostPerToken",
    "TotalCost",
    "CostBreakdown",
    "Latency",
    "Throughput",
    "RateLimit",
    "ErrorType",
    "LLMErrorCode",
    "RetryAfter",
    "ModelConfig",
    "ProviderConfig",
    "LLMConfig",
    
    # LLM protocols
    "LLMProvider",
    "LLMModel",
    "LLMRequest",
    "LLMResponse",
    "Message",
    "StreamingResponse",
    "StreamingChunk",
    "ChatProvider",
    "CompletionProvider",
    "EmbeddingProvider",
    "ChatRequest",
    "ChatResponse",
    "CompletionRequest",
    "CompletionResponse",
    "EmbeddingRequest",
    "EmbeddingResponse",
    
    # LLM utilities
    "create_message",
    "calculate_token_cost",
    "create_usage_dict",
    "validate_model_config",
]
