gemini_cloud_log_monitor:
  default_model_selection:
    triage_model: "gemini-1.5-flash-001"
    analysis_model: "gemini-1.5-pro-001"
    classification_model: "gemini-2.5-flash-lite"

  default_github_config:
    repository: "owner/repo"
    base_branch: "main"

  logging:
    log_level: "INFO"
    json_format: false
    log_file: null

  services:
    - service_name: "billing-service"
      project_id: "your-gcp-project"
      location: "us-central1"
      subscription_id: "billing-logs-subscription"
      # Optional: Override default model_selection or github for this service
      # model_selection:
      #   triage_model: "gemini-1.5-flash-special"
      # github:
      #   repository: "owner/billing-repo"

    - service_name: "auth-service"
      project_id: "your-gcp-project"
      location: "us-central1"
      subscription_id: "auth-logs-subscription"
      # This service will use default_model_selection and default_github_config
