schema_version: 1.0.0

global_config:
  max_throughput: 250
  error_threshold: 0.01
  enable_metrics: true
  enable_health_checks: true
  buffer_strategy: memory
  max_memory_mb: 64
  retry_attempts: 3
  retry_delay: 2.0
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60

# Logging configuration
logging:
  log_level: DEBUG # Change from INFO to DEBUG
  json_format: true
  log_file: null

sources:
  - name: sre-agent-logs
    type: file_system
    enabled: true
    priority: 10
    max_retries: 3
    retry_delay: 2.0
    timeout: 30.0
    circuit_breaker_enabled: true
    rate_limit_per_second: 25
    config:
      file_path: /tmp/sre-dogfooding/sre_agent_1.log
      file_pattern: "*.log"
      watch_mode: true
      encoding: utf-8
      buffer_size: 2048
      max_memory_mb: 64

# Agent-specific configuration
agent_config:
  name: "dogfood-meta-monitor-agent"
  role: "self-healing"
  target_repository: "current" # Current repository (self-healing)
  branch_prefix: "dogfood-self-fix"
  pr_labels: ["dogfood-self-healing", "auto-generated"]
  pr_title_template: "Self-healing fix for {component} crash"
  pr_body_template: |
    ## Auto-generated self-healing fix

    **Issue Details:**
    - Component: {component}
    - Error Type: {error_type}
    - Severity: {severity}

    **Root Cause Analysis:**
    {analysis}

    **Proposed Fix:**
    {fix_description}

    **Self-Healing Validation:**
    - [ ] Agent crash resolved
    - [ ] No new errors introduced
    - [ ] Agent functionality restored

    Generated by SRE Agent Instance #2 (Meta-Monitor)

  # Model selection for this agent (more conservative for self-healing)
  model_config:
    primary_model: "llama3.1:70b"
    fallback_models: ["llama3.1:8b", "codellama:13b"]
    max_tokens: 6000
    temperature: 0.05 # Lower temperature for more conservative fixes
    provider: "ollama"
    base_url: "http://localhost:11434"

  # GitHub integration
  default_github_config:
    repository: "current"
    base_branch: "main"
    auto_create_pr: true
    auto_merge: false
    require_review: true

  # Self-healing specific settings
  self_healing_config:
    max_fix_attempts: 3
    fix_cooldown_seconds: 300 # 5 minutes between fix attempts
    critical_components: ["triage_agent", "analysis_agent", "remediation_agent"]
    ignore_patterns:
      - "expected.*error"
      - "handled.*exception"
      - "retry.*attempt"

  # Validation settings
  validation_config:
    run_tests: true
    test_command: "python -m pytest tests/ -x" # Stop on first failure
    timeout_seconds: 600 # Longer timeout for self-healing tests
    require_all_tests_pass: true
    restart_agent_after_fix: true
