schema_version: 1.0.0

global_config:
  max_throughput: 500
  error_threshold: 0.02
  enable_metrics: true
  enable_health_checks: true
  buffer_strategy: memory
  max_memory_mb: 128
  retry_attempts: 3
  retry_delay: 1.0
  circuit_breaker_threshold: 10
  circuit_breaker_timeout: 30

# Logging configuration
logging:
  log_level: DEBUG # Change from INFO to DEBUG
  json_format: true
  log_file: null

sources:
  - name: dogfood-service-logs
    type: file_system
    enabled: true
    priority: 10
    max_retries: 3
    retry_delay: 1.0
    timeout: 30.0
    circuit_breaker_enabled: true
    rate_limit_per_second: 50
    config:
      file_path: /tmp/sre-dogfooding/dogfood_service.log
      file_pattern: "*.log"
      watch_mode: true
      encoding: utf-8
      buffer_size: 4096
      max_memory_mb: 100

# Agent-specific configuration
agent_config:
  name: "dogfood-fixer-agent"
  role: "remediation"
  target_repository: "current" # Current repository
  branch_prefix: "dogfood-fix"
  pr_labels: ["dogfood-demo", "auto-generated"]
  pr_title_template: "Fix {error_type} in dogfood service"
  pr_body_template: |
    ## Auto-generated fix for {error_type}

    **Error Details:**
    - Type: {error_type}
    - Endpoint: {endpoint}
    - Category: {category}

    **Root Cause Analysis:**
    {analysis}

    **Proposed Fix:**
    {fix_description}

    **Testing:**
    - [ ] Automated tests pass
    - [ ] Manual verification completed
    - [ ] No regression introduced

    Generated by SRE Agent Instance #1 (Dogfood Fixer)

  # Model selection for this agent
  model_config:
    primary_model: "llama3.1:8b"
    fallback_models: ["llama3.1:70b", "codellama:7b"]
    max_tokens: 4000
    temperature: 0.1
    provider: "ollama"
    base_url: "http://localhost:11434"

  # GitHub integration
  default_github_config:
    repository: "current"
    base_branch: "main"
    auto_create_pr: true
    auto_merge: false
    require_review: true

  # Validation settings
  validation_config:
    run_tests: true
    test_command: "cd examples/dogfooding/dogfood_service && python -m pytest tests/"
    timeout_seconds: 300
    require_all_tests_pass: true
